language: node_js
node_js:
- '4'
sudo: false
cache:
  directories:
  - node_modules
before_install:
- npm config set spin false
- npm install -g bower
- bower --version
- npm install phantomjs-prebuilt
- node_modules/phantomjs-prebuilt/bin/phantomjs --version
install:
- npm install
- bower install
script:
- npm test
before_deploy:
- npm run build
deploy:
  provider: s3
  access_key_id:
    secure: JNZk6Xhcnm1vrN1seDhTJSoduy0d9Cxv2dDWoPMT3PpRw49x4Kp7i55jSSOa2n/qYoN+VHWBB/CkX4sq1F6/Bn66NGPA9vySx/n7/Yfcc2SrcFHVOa4ne6E5aAZZhDv60ebmOVRykD2yWQkukm0qMfYE+QdtMEIYb3cZJLoti4Hp0AqZp+WMMSNJB9HHrZOzLFqVXHtd+JWR4iWd2VAOkxnSiIoblFDxEBe2CNx+QuyOinCTqXzrisltvwgcy8Mfzg6RHfn+KjQWQMIwNDurlgDVD5ah9Ek/nEodIvC1LXzZq8dsI2hg/WMGk1tdDGB2NOTkkpoiw0sskHoLpA510E3fufM+7C0FCwCqjTcItwXQpSSDaWwDrYWHfqFz1ppr0jVr6tYEgH2rCWT50HdLcgueciuRZM8hOUFKKupcNIVNZrQLFiLBQONTWAOm/VjX55hE8pZ+p4KiDM9pi2QkYRgncl7X4jBfcDdmmNF46Llv6N9hJeJ7N4SUij/LQSpxWdv3l6riy+9jpiXnC2VfYjYEeM/ZUSCheXqEB/BHb/YNiMQEFV4UKoqWZlrxfkoPlOcPPgPm3RbgFIlLaOzNeTpWKUk0/urWpw+RkOhYuoh1MJ1u0v/XS9V4orAm1tpoKHwNcP1ZS+xMj9NqQTil2dA70C3hfg7poi2k4BTjv5E=
  secret_access_key:
    secure: MgWgJtiO3OcEL8f6W3ZeVo1ZM/VsCSdI+TPEtN4zsg9HonYK6Jmnfwhemkr8tzc+ZTjx61EeKJVPQ9HQkXhnMT+OKymraHtbITriFquX3zUzT2yIrYs5Ts2Ii9aucec3BRGGgwaKJ4MU4VQbebyTRnILFb+0OHPO3bMiKyTBbdPkylO2Pu5siUx5nlgpQBaiOIn6thYJnKQ8hkPuGCZpMLjI/NGsSE3PIvzziHwLl+PNXxniZxGz+VPp2YR10Oz9CRlFE2HLaTIwZhwY0mhjHEiGwQENEfTRq8mLGKu1ZOrMRDjcuTlTgZsRVV1z2ChXScAVgtoMdje83o7Og7C1pclDIJuMVN2qIm27tOf6wN8foVML7622x9uCv7AgDKETnWXp/K0h6LiLZBUh6KySM7ap9+Vr1mD8VMVQalNhUqJ59NZK4S3dW4DvpYwt28BbwArue2apKIkTFblpS36YragmzKKVfh2EtVyHsQPezp96Md6ludzc1EKitghHsjbMVgiTBm0lWG8Wk79vguNloxz1dxuhNRg3JIR6OHefHJ/7yC1MEVlMWhXdAoGnHUAl+9lN6BBvdIG+pkY4Qu7F3OCqYLrpK1kWb904LtPjxrK3JqnLxVr3EidEfRyl6fvzFgLbFvPpV1rEicw466+3u7uQCWLlExkEoPmbnKAeTqQ=
  bucket: cloudfront-app
  local_dir: dist
  upload_dir: master
  skip_cleanup: true
  region: us-west-2
notifications:
  slack:
    on_success: change
    on_failure: change
    secure: 4SlBJ6orRHmvegWls56VHznJSGnSm2eQNGH1Mq7knuCMFksnopaxK6NHNaxZvFPyDV35juK0PyB2kZVJHgltMzGSdyL9cUXQw4xc2SbUXXk+1XTggegXyrFHg3IwXbR3cxSqLi32BvH1EVPGXbZG6PQWEFnnrj3b3mVpoSrNTGSI/uitbsHwqZgBnztBMITsA0gKVVx1cCHLi4fPY/W1zDXdybicVp2/Cj18yqM6/9cje9wwRdj6fwHAC0r4cg9OEN28ouFzubH+sz0EiQmotd6McNL2PWNihxPpIsVO9lCwWO/n7tCCatcnhuCilgKefvza8cDC5+1G8wRQUPYYWoIgEA9JfUeOBaxzAOG/IVt0Nzi7eN/ww2ibArUpYsE2X+Mfyj0R4U+leF8U1S61YRD3Edj55Hy6CYM8LxT7t0Xjsmwo4ZNys1HD2TgA4EPuTWmn6lKM0IWnZHERLBGHSrpYR5YRVt3d4NcJArVOESyfktBrXjKnkefSWusCvVFiG2rwL0QWU0UpEjQaJMRrRN2aLokPLwYGk34B+MiEkIGbJU3cLoef3xMNwQ/RCDT0fbqCj0xjEdoo+mOuOFhbSQPsLKXrLlZno+r7/UfNtNZSLAKDm1KF0uugdRj54reIBPSRZVle/TUmIbk+gooYphsbglLDT10TSEyFTSHh1MU=
